version: '3'

networks:
  observabilidade:
    driver: bridge

services:

  mysql:
    container_name: mysql_observabilidade
    image: mysql:8.0
    restart: always
    ports:
      - "3314:3306"
    environment:
      - MYSQL_DATABASE=observabilidade
      - MYSQL_USER=mysql001
      - MYSQL_PASSWORD=mysql001
      - MYSQL_ROOT_PASSWORD=root010203
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - observabilidade

  redis:
    image: redis:alpine
    container_name: redis_observabilidade
    expose:
      - 6379
    networks:
      - observabilidade

  prometheus:
    container_name: prometheus_observabilidade
    image: ubuntu/prometheus
    ports:
      - "30090:9090"
    volumes:
      - ./.docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    environment:
      - TZ=UTC
    networks:
      - observabilidade

  grafana:
    container_name: grafana_observabilidade
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: '104'
    networks:
      - observabilidade


  jaeger:
    container_name: jaeger_observabilidade
    image: jaegertracing/all-in-one:latest
    ports:
      - "4319:4318"
      - "16686:16686" # For Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - observabilidade

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./.docker/otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension

